services:
  mysql:
    image: mysql:8.0
    container_name: student-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
      MYSQL_USER: student
      MYSQL_PASSWORD: studentpass
    ##ports:
      ##- "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: student-backend
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    environment:
      DB_HOST: mysql
      DB_USER: student
      DB_PASSWORD: studentpass
      DB_NAME: studentdb

volumes:
  mysql_data: