name: CD - Deploy on EC2

on:
  workflow_dispatch:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: SSH into EC2 and Run Basic Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected via GitHub Actions"
            whoami
            pwd

      - name: Verify Docker Installation and Permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Docker version ==="
            echo docker --version

            echo "=== Docker service status ==="
            systemctl is-active docker

            echo "=== Docker permission check ==="
            docker ps